package Tarot.ModelPack;

public enum TarotAction {
    JEU_MIXED,
    JEU_CUT,
    CARDS_DISTRIBUTED,
    CARD_MOVED_TO_CHIEN,
    CARD_MOVED,
    PLAYER_REVERTED,
    PLAYER_ORGANIZED,
    PETIT_SEC_DETECTED,
    ACTION_CHOSEN,
    CHIEN_REVERTED,
    CARD_ADDED_GAP,
    GAP_DONE,
    DISTRIBUTION_DONE
}
