package Tarot;

public enum TarotAction {
    DECK_MIXED,
    DECK_CUT,
    CARDS_DISTRIBUTED,
    CARD_MOVED_FROM_DECK,
    CARD_MOVED,
    PLAYER_REVERTED,
    PLAYER_ORGANIZED,
    PETIT_SEC_DETECTED,
    ACTION_CHOSEN,
    CHIEN_REVERTED,
    CARD_ADDED_GAP,
    GAP_DONE,
    DISTRIBUTION_DONE
}
